modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/CreativeMD/NoDurabilityLost/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="nodurabilitylost"
    logoFile="nodurabilitylost.png"
    version="1.0.0"
    displayName="NoDurabilityLost"
    displayURL="https://modrinth.com/mod/nodurabilitylost"
    authors="CreativeMD"
    description='''A mod which prevents a tool from taking damage if there is no speed benefit in breaking the block.'''

[[dependencies.nodurabilitylost]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nodurabilitylost]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

